### ISSUE TITLE
Lost zeros using SIWithDigits with 0 decimals 200.0 becomes "2"

### ISSUE THREAD

**Issue by phfix** [dustin/go-humanize#106]
Hi,
I have noticed that the function humanize.SIWithDigits doesn't handle when the value to be rounded doesn't have any decimals.

Example:
fmt.Printf("20   -> %s\n", humanize.SIWithDigits(20.0, 0, "Unit"))
fmt.Printf("200  -> %s\n", humanize.SIWithDigits(200.0, 0, "Unit"))

Output:
20   -> 2 Unit
200  -> 2 Unit

I think the function  stripTrailingZeros needs to check if "." is in the string at all

Workaround for now it to not use 0 decimals

**Comment by dustin** [comment]
Thanks for reporting this.  Was kind of egregious.

**Comment by williambrode** [comment]
@dustin Don't you need to add a new tag for us to get this fix?  I see there is only v1.0.0 from 2018.

**Comment by dustin** [comment]
I just pushed a new tag v1.0.1.  Let me know if that works for you.

**Comment by williambrode** [comment]
Yes, that did the trick ```go get github.com/dustin/go-humanize``` now pulls down v1.0.1
