### ISSUE TITLE
no space between bytes and units

### ISSUE THREAD

**Issue by nhooyr** [dustin/go-humanize#32]
We should revert #21 for bytes or have some sort of configuration. I've never seen a space before like this.

http://www.staples.ca/en/USB-Flash-Drives/Kingston/cat_CL200543_2-CA_1_20001%3Ffids%3D4214939354

http://www.bestbuy.ca/en-CA/category/desktop-memory-ram/20359.aspx

It just looks so weird to me. I've reverted the commit in my fork but I'd be nice to see it in the main repo.

**Comment by dustin** [comment]
It looks weird to me as well, but I don't set the standards.

Do you have a reference (other than random web developers at stores) for
the correct format?  Even if it's not hugely useful, it's surely best to do
the right thing WRT SI.

**Comment by shurcooL** [comment]
> I've never seen a space before like this

Here's a screenshot from an OS X "About this Mac" view:

![image](https://cloud.githubusercontent.com/assets/1924134/14091746/ebd8390c-f4f6-11e5-9ec2-79851da2b9a7.png)

It's better and easier to follow a standard, SI in this case, than to try to invent one's own ad-hoc solutions. If you need custom behavior for a specific app, you should do something custom. This library tries to stay general and useful to most people, and following SI standard is a good decision IMO.

**Comment by nhooyr** [comment]
Alright, gonna close then.
