### ISSUE TITLE
BigCommaf is not possible ?

### ISSUE THREAD

**Issue by pyed** [dustin/go-humanize#35]
I noticed that lack of this function, why it is not there ?

**Comment by dustin** [comment]
None of the functions were there before they were written.  :)

**Comment by pyed** [comment]
Alright, I'll take that as a challenge

**Comment by dustin** [comment]
Great.  Many of the requests that come through require breaking existing APIs.   As this is a new one, you just need to make it look like existing ones as best as reasonable.  It's quite easy to write a few tests and then just make them work.

**Comment by pyed** [comment]
https://github.com/dustin/go-humanize/pull/36
