### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by distantbit** [dustin/go-humanize#38]
When i try to get the package via `go get github.com/dustin/go-humanize` then there will be an error

```
# github.com/dustin/go-humanize
../../dustin/go-humanize/comma.go:105: undefined: big.Float
```
I am on an ubuntu trusty machine with golang packages installed via apt.

**Comment by distantbit** [comment]
I fixed it by removing the installation via apt and used the current (1.6.2) go binaries from their homepage instead

**Comment by shurcooL** [comment]
Installing Go is indeed best done from its website. Some package managers tend to have very outdated versions of it.
