### ISSUE TITLE
FormatFloat() overflow bug on 32bit systems

### ISSUE THREAD

**Issue by TerraTech** [dustin/go-humanize#46]
I ran into a bug tonight compiling a 32bit version and found ```FormatFloat()``` was overflowing an int somewhere.  My program is dealing with nanosecond time calculations and I'm humanizing a scaling factor.

Interestingly enough, ```Commaf()``` doesn't have the same problem.
```go
package main
import (
	"fmt"
	"math"
	"github.com/dustin/go-humanize"
)

func main() {
	var a float64 = 52746220055.92342
	fmt.Println(math.MaxFloat64)
	fmt.Println(humanize.Commaf(a))
	fmt.Println(">>> " + humanize.FormatFloat("#,###.##", a))
}
```
```sh
#64bit
$ go run main.go
1.7976931348623157e+308
52,746,220,055.92342
>>> 52,746,220,055.92

#32bit
$ GOARCH=386 go run main.go
1.7976931348623157e+308
52,746,220,055.92342
>>> -2,147,483,648.92
```

**Comment by shurcooL** [comment]
There are 3 places or so inside `humanize.FormatFloat` that use `int`. I suspect that's where the issue likely lies. A fix could be to always use `int64`.

**Comment by dustin** [comment]
Anyone happen to know how to force 32-bit for tests?  Guess I need more CI
here.  I've got a few arm boxes I run at home I could employ.

**Comment by shurcooL** [comment]
> Anyone happen to know how to force 32-bit for tests?

Perhaps something like:

```
GOARCH=386 go test
```
