### ISSUE TITLE
count time delta

### ISSUE THREAD

**Issue by anarcat** [dustin/go-humanize#48]
"x <unit> ago" is great, but i would like to count elapsed time, more like "4 hours, 3 minutes and 2 seconds". is this something this package should be doing?

**Comment by dustin** [comment]
I don't think there's a huge advantage over https://play.golang.org/p/v5fINIqPAF

**Comment by anarcat** [comment]
duh. i see. i was using the wrong format string in my printouts, my apologies for the noise: https://play.golang.org/p/3EHpceBuye
