### ISSUE TITLE
IBytes returns 4.9GiB for 5248122880 bytes instead of 5GiB

### ISSUE THREAD

**Issue by krisis** [dustin/go-humanize#51]
## Sample program
```go
package main

import (
        "fmt"
        humanize "github.com/dustin/go-humanize"
)

func main() {
        fmt.Println(humanize.IBytes(5248122880))
}

```

## Current behaviour
The above sample program compiled with master branch at commit-id `259d2a102b871d17f30e3cd9881a642961a1e486` gives `4.9 GiB`.

## Expected behaviour
The result should be `5 GiB`.

**Comment by shurcooL** [comment]
5248122880 / 1024 / 1024 / 1024 = 4.8876953125.

Why do you expect it to be 5.0 GiB instead of 4.9 GiB?

Also see http://www.wolframalpha.com/input/?i=5248122880+bytes:

> 4.888 GiB (gibibytes)

**Comment by krisis** [comment]
@shurcooL You are right. I made the same mistake multiple times. I tested my incorrect hypothesis, that 5000 MiB is 5GiB, using `bc`, a haskell library similar to this one. I came to the same (incorrect) conclusion. Embarrassingly enough, I didn't realise until you pointed out. Apologies.

**Comment by shurcooL** [comment]
No worries! Thanks for taking the time to report anyway. :)
