### ISSUE TITLE
Add support for converting duration to HH:MM:SS

### ISSUE THREAD

**Issue by macnibblet** [dustin/go-humanize#52]

**Comment by shurcooL** [comment]
This seems pretty similar to #48.

Can you elaborate on how this would be more useful than the [default string format](https://godoc.org/time#Duration.String) for a `time.Duration`, which has the form "72h3m0.5s".

**Comment by macnibblet** [comment]
I needed the specific format `hh:mm:ss` which is archiveable via `time.Time{}.Add(time.Duration(duration) * time.Second).Format("15:04:05")`
