### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by xiang90** [dustin/go-humanize#56]
go-humanize is a great project that a lot of go projects depend on. Do you mind to tag a release to make it easier to vendor? Thank you!

**Comment by alnsn** [comment]
|I concur. I came across your project because I'm making a package that depends on your project and I need a proper release to make a proper package.

**Comment by fd0** [comment]
Ping, could you please tag a release? :)

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by kyleconroy** [comment]
Pinging again here as well

**Comment by dustin** [comment]
I tagged a v1.0.0 -- sorry for massive delays.

**Comment by fd0** [comment]
Thank you very much for your work!
