### ISSUE TITLE
Add simple English-language string manipulation functions (e.g., PluralWord)

### ISSUE THREAD

**Issue by clconway** [dustin/go-humanize#57]
I would like to add some simple English-language output functions to this library, e.g.,

```go
func Plural(quantity int, singular, plural string) string
//  Plural(1, "foo", "foos") ==> "1 foo"
//  Plural(2, "foo", "foos") ==> "2 foos"
//  Plural(2, "foo", "") ==> "2 foos"  (simple default pluralization)
```
```go
func WordSeries(words []string, conjunction string) string
// WordSeries([]string{"foo", "bar"}, "and") ==> "foo and bar"
//  WordSeries([]string{"foo", "bar", "qux"}, "and") ==> "foo, bar and qux"
```

These aren't really in-scope for the current version of the library, but are broadly useful in similar situations (e.g., user/debugging output) and seem like a kind of "humanization".

I can contribute and maintain these functions if you are willing to accept a PR.

**Comment by dustin** [comment]
Hmm...   `WordSeries` seems to already be starting an Oxford comma debate.  :)

**Comment by clconway** [comment]
I'm happy to add `OxfordWordSeries` as well. ;-)

**Comment by dustin** [comment]
@shurcooL Do you have any objections here?  I want the Oxford comma, but it seems like a generally useful thing when dealing with sets.

**Comment by shurcooL** [comment]
I'm always cautious about expanding the surface area of an API and increasing scope of a library. The addition should be justified.

But, I don't have strong objections.

If the implementation is not so trivial that anyone can implement it trivially in their project, and if you think this is going to be used by enough people, then `humanize` will become better if this is added.

I don't have a need for this at this time, so it's hard for me to say whether it's useful.

**Comment by shurcooL** [comment]
Also, since @clconway offered kindly not only to contribute, but also to maintain these, that makes it easier to say yes.
