### ISSUE TITLE
Option to elide space between value and units

### ISSUE THREAD

**Issue by mcandre** [dustin/go-humanize#80]
Please include an option to remove spaces between values and units.

**Comment by dustin** [comment]
This came up in #32 as a response to #21 where we (slightly reluctantly) decided to comply with SI standards.  If you wish to deviate, it makes sense to write a small space absorbing wrapper.

There's no natural place for options now, so we'd have to make a new API just to deal with non-standard presentations that can easily be done by creating a local API that absorbs space (e.g., [here's an example](https://play.golang.org/p/LGiARbtCdWu) `io.Writer` that eats spaces).
