### ISSUE TITLE
PluralWord should return singular word with a 0 quantity

### ISSUE THREAD

**Issue by LudovicTOURMAN** [dustin/go-humanize#83]
**What:**
When using the functions `Plural`/`PluralWord` with a quantity of 0, those functions return the plural word.

**Why:**
`Plural` function is based on `PluralWord` function. This last one is strictly checking that the [quantity is equal to 1](https://github.com/dustin/go-humanize/blob/master/english/words.go#L30) in order to return the singular word.
However, it should also return the singular word in case the value is 0.

Ex: `2 pending requests`, `1 pending request`, `0 pending request`

**Comment by BrianLeishman** [comment]
Using the singular form of a word with 0 wouldn't be grammatically correct

**Comment by dustin** [comment]
Yes.  Singular is only valid for "single" results.  For all others, there's plural.

It's a confusing bit of English.  "Plural" refers to more than one.  "Singular" refers to exactly one.  Zero matches neither of those, but we use the plural form in these cases.

**Comment by LudovicTOURMAN** [comment]
Ok, thanks for your explanation guys.
A new rule to add to my English grammar :grin:
